version: '3'

services:
  web:
    build: ./nginx
    container_name: nginx-docker-stack
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
#  php:
#    container_name: php-docker-stack
#    build: ./php7.2
#    volumes:
#      - .:/app
#      - ./php7.2/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini
#      - ./php7.2/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini
#  php:
#    container_name: php-docker-stack
#    build: ./php7.1
#    volumes:
#      - .:/app
#      - ./php7.1/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini
#      - ./php7.1/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini
#  php:
#    container_name: php-docker-stack
#    build: ./php7.0
#    volumes:
#      - .:/app
#      - ./php7.0/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini
#      - ./php7.0/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini
#  php:
#    container_name: php-docker-stack
#    build: ./php5.6
#    volumes:
#      - .:/app
#      - ./php5.6/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini
#      - ./php5.6/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini
#  php:
#    container_name: php-docker-stack
#    build: ./php5.5
#    volumes:
#      - .:/app
#      - ./php5.5/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini
#      - ./php5.5/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini
  php:
    container_name: php-docker-stack
    build: ./php5.4
    volumes:
      - .:/app
      - ./php5.4/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini
      - ./php5.4/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini
  db:
    build: ./mariadb
    container_name: db-docker-stack
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: secret
      MYSQL_DATABASE: site
      MYSQL_PASSWORD: secret
    user: "1000:50"
    volumes:
      - .:/app
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
